services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    ports:
      - "8080:80"
    environment:
      - DOMAINE_NAME=${DOMAINE_NAME}


  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql

secrets:
  db_password:
    file: ${DB_PASSWORD_FILE}
  db_root_password:
    file: ${DB_ROOT_PASSWORD_FILE}

volumes:
  db_data:

